version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/verath/owbot-bot
    steps:
      - checkout
      - run: go build -v
      - run: go vet $(go list | grep -v vendor)
      - run: go test -v -race -timeout 30s $(go list | grep -v vendor)

  docker_publish:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish verath/owbot-bot:latest docker image
          command: |
            docker build --pull -t verath/owbot-bot .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push verath/owbot-bot

  gce_deploy:
    docker:
      - image: google/cloud-sdk:alpine
    working_directory: /go/src/github.com/verath/owbot-bot
    steps:
      - checkout
      - run:
          name: gcloud CLI auth
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project "owbot-bot"
            gcloud config set compute/zone "us-west1-a"
      - run:
          name: Upload and execute run_owbot.sh script on "owbot" GCE instance
          command: |
            gcloud compute scp scripts/run_owbot.sh owbot:~/run_owbot.sh
            gcloud compute ssh owbot --command "DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN} bash ./run_owbot.sh"

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
      - docker_publish:
          requires:
            - build
          filters:
            branches:
              only: master
      - gce_deploy:
          requires:
            - docker_publish
          filters:
            branches:
              only: master
